from typing import Any, Dict, List

from skeval.metrics.metrics import compute_metrics


class Evaluator:
    """Evaluates the predictions of a skeval classifier against ground truth."""

    def __init__(self):
        pass

    def evaluate(
        self, predictions: List[str], ground_truth: List[str]
    ) -> Dict[str, Any]:
        """
        Evaluate predicted semantic classes.

        Args:
            predictions: List of labels generated by the SentenceClassifier.
            ground_truth: The actual correct labels for the data.

        Returns:
            A comprehensive dictionary of performance metrics.
        """
        if len(predictions) != len(ground_truth):
            raise ValueError(
                f"Mismatch in lengths: "
                f"{len(predictions)} predictions vs "
                f"{len(ground_truth)} truth labels."
            )

        results = compute_metrics(ground_truth, predictions)
        return results
